# Generated by Django 5.2.6 on 2025-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('car_Name', models.CharField(max_length=10)),
                ('carID', models.IntegerField(primary_key=True, serialize=False)),
                ('fuelTupe', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=6)),
                ('brand', models.CharField(max_length=8)),
            ],
        ),
    ]
